table dim_model

	column model_key
		dataType: string
		isHidden
		isKey
		summarizeBy: none
		sourceColumn: model_key

	column model_name
		dataType: string
		summarizeBy: none
		sourceColumn: model_name

	column model_version
		dataType: string
		summarizeBy: none
		sourceColumn: model_version

	column provider
		dataType: string
		summarizeBy: none
		sourceColumn: provider

	column modality
		dataType: string
		summarizeBy: none
		sourceColumn: modality

	partition dim_model = m
		mode: import
		source =
			let
				Src = Csv.Document(File.Contents("C:\\Users\\snatesan\\ai-finops-powerbi\\AIFinOps.SemanticModel\\data\\dim_model.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Hdr = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Hdr, {{"model_key", type text}, {"model_name", type text}, {"model_version", type text}, {"provider", type text}, {"modality", type text}})
			in
				Typed
