table dim_platform

	column platform_key
		dataType: string
		isHidden
		isKey
		summarizeBy: none
		sourceColumn: platform_key

	column platform_name
		dataType: string
		summarizeBy: none
		sourceColumn: platform_name

	column billing_model
		dataType: string
		summarizeBy: none
		sourceColumn: billing_model

	column native_unit
		dataType: string
		summarizeBy: none
		sourceColumn: native_unit

	column has_token_telemetry
		dataType: boolean
		summarizeBy: none
		sourceColumn: has_token_telemetry

	column has_native_cost
		dataType: boolean
		summarizeBy: none
		sourceColumn: has_native_cost

	column is_variable_cost
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_variable_cost

	column data_source
		dataType: string
		summarizeBy: none
		sourceColumn: data_source

	partition dim_platform = m
		mode: import
		source =
			let
				Src = Csv.Document(File.Contents("C:\\Users\\snatesan\\ai-finops-powerbi\\AIFinOps.SemanticModel\\data\\dim_platform.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Hdr = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Hdr, {{"platform_key", type text}, {"platform_name", type text}, {"billing_model", type text}, {"native_unit", type text}, {"has_token_telemetry", type logical}, {"has_native_cost", type logical}, {"is_variable_cost", type logical}, {"data_source", type text}})
			in
				Typed
