table dim_identity

	column identity_key
		dataType: string
		isHidden
		isKey
		summarizeBy: none
		sourceColumn: identity_key

	column display_name
		dataType: string
		summarizeBy: none
		sourceColumn: display_name

	column principal_type
		dataType: string
		summarizeBy: none
		sourceColumn: principal_type

	column upn
		dataType: string
		summarizeBy: none
		sourceColumn: upn

	column github_login
		dataType: string
		summarizeBy: none
		sourceColumn: github_login

	column team
		dataType: string
		summarizeBy: none
		sourceColumn: team

	column business_unit
		dataType: string
		summarizeBy: none
		sourceColumn: business_unit

	column cost_center_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: cost_center_key

	partition dim_identity = m
		mode: import
		source =
			let
				Src = Csv.Document(File.Contents(DataFolder & "dim_identity.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Hdr = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Hdr, {{"identity_key", type text}, {"display_name", type text}, {"principal_type", type text}, {"upn", type text}, {"github_login", type text}, {"team", type text}, {"business_unit", type text}, {"cost_center_key", type text}})
			in
				Typed
