table dim_cost_center

	column cost_center_key
		dataType: string
		isHidden
		isKey
		summarizeBy: none
		sourceColumn: cost_center_key

	column cost_center_name
		dataType: string
		summarizeBy: none
		sourceColumn: cost_center_name

	column business_unit
		dataType: string
		summarizeBy: none
		sourceColumn: business_unit

	column owner_upn
		dataType: string
		summarizeBy: none
		sourceColumn: owner_upn

	partition dim_cost_center = m
		mode: import
		source =
			let
				Src = Csv.Document(File.Contents("C:\\Users\\snatesan\\ai-finops-powerbi\\AIFinOps.SemanticModel\\data\\dim_cost_center.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Hdr = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Hdr, {{"cost_center_key", type text}, {"cost_center_name", type text}, {"business_unit", type text}, {"owner_upn", type text}})
			in
				Typed
