table dim_data_source
	/// Catalogue of every extractable AI telemetry signal per platform: what can be
	/// pulled, from which API, at what identity grain and cost fidelity, and whether it
	/// is REAL / AVAILABLE / MOCK / ROADMAP today. Disconnected reference (no relationship).

	column platform
		dataType: string
		summarizeBy: none
		sourceColumn: platform

	column signal_category
		dataType: string
		summarizeBy: none
		sourceColumn: signal_category

	column signal
		dataType: string
		summarizeBy: none
		sourceColumn: signal

	column source_api
		dataType: string
		summarizeBy: none
		sourceColumn: source_api

	column grain
		dataType: string
		summarizeBy: none
		sourceColumn: grain

	column identity_granularity
		dataType: string
		summarizeBy: none
		sourceColumn: identity_granularity

	column cost_fidelity
		dataType: string
		summarizeBy: none
		sourceColumn: cost_fidelity

	column retention
		dataType: string
		summarizeBy: none
		sourceColumn: retention

	/// REAL (live now) · AVAILABLE (API exists, not yet wired) · MOCK (needs SKU/policy) · ROADMAP
	column availability
		dataType: string
		summarizeBy: none
		sourceColumn: availability

	column notes
		dataType: string
		summarizeBy: none
		sourceColumn: notes

	measure 'Extractable Signals' = COUNTROWS(dim_data_source)
		formatString: #,0

	/// Signals live in the model today (REAL data source).
	measure 'Signals Live (REAL)' =
		CALCULATE(COUNTROWS(dim_data_source), dim_data_source[availability] = "REAL")
		formatString: #,0

	/// Signals whose API exists and could be wired without new licensing.
	measure 'Signals Available' =
		CALCULATE(COUNTROWS(dim_data_source), dim_data_source[availability] = "AVAILABLE")
		formatString: #,0

	partition dim_data_source = m
		mode: import
		source =
			let
				Src = Csv.Document(File.Contents(DataFolder & "extractable_data_catalog.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Hdr = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Hdr, {{"platform", type text}, {"signal_category", type text}, {"signal", type text}, {"source_api", type text}, {"grain", type text}, {"identity_granularity", type text}, {"cost_fidelity", type text}, {"retention", type text}, {"availability", type text}, {"notes", type text}})
			in
				Typed
