table dim_rate_card

	column rate_key
		dataType: string
		isHidden
		isKey
		summarizeBy: none
		sourceColumn: rate_key

	column platform
		dataType: string
		summarizeBy: none
		sourceColumn: platform

	column unit_type
		dataType: string
		summarizeBy: none
		sourceColumn: unit_type

	column model
		dataType: string
		summarizeBy: none
		sourceColumn: model

	column unit_price_usd
		dataType: double
		formatString: \$#,0.000000
		summarizeBy: none
		sourceColumn: unit_price_usd

	column effective_from
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: effective_from

	column currency
		dataType: string
		summarizeBy: none
		sourceColumn: currency

	column source
		dataType: string
		summarizeBy: none
		sourceColumn: source

	column note
		dataType: string
		summarizeBy: none
		sourceColumn: note

	partition dim_rate_card = m
		mode: import
		source =
			let
				Src = Csv.Document(File.Contents("C:\\Users\\snatesan\\ai-finops-powerbi\\AIFinOps.SemanticModel\\data\\dim_rate_card.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Hdr = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Hdr, {{"rate_key", type text}, {"platform", type text}, {"unit_type", type text}, {"model", type text}, {"unit_price_usd", type number}, {"effective_from", type date}, {"currency", type text}, {"source", type text}, {"note", type text}})
			in
				Typed
