table dim_date
	dataCategory: Time

	column date_key
		dataType: dateTime
		formatString: yyyy-mm-dd
		isKey
		summarizeBy: none
		sourceColumn: date_key

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: string
		summarizeBy: none
		sourceColumn: quarter

	column month
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: month

	column month_name
		dataType: string
		sortByColumn: month
		summarizeBy: none
		sourceColumn: month_name

	column day
		dataType: int64
		summarizeBy: none
		sourceColumn: day

	column day_name
		dataType: string
		summarizeBy: none
		sourceColumn: day_name

	column is_weekday
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_weekday

	column year_month
		dataType: string
		summarizeBy: none
		sourceColumn: year_month

	partition dim_date = m
		mode: import
		source =
			let
				Src = Csv.Document(File.Contents("C:\\Users\\snatesan\\ai-finops-powerbi\\AIFinOps.SemanticModel\\data\\dim_date.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Hdr = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Hdr, {{"date_key", type date}, {"year", Int64.Type}, {"quarter", type text}, {"month", Int64.Type}, {"month_name", type text}, {"day", Int64.Type}, {"day_name", type text}, {"is_weekday", type logical}, {"year_month", type text}})
			in
				Typed
