table dim_environment

	column environment_key
		dataType: string
		isHidden
		isKey
		summarizeBy: none
		sourceColumn: environment_key

	column environment_name
		dataType: string
		summarizeBy: none
		sourceColumn: environment_name

	column is_production
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_production

	column sla_tier
		dataType: string
		summarizeBy: none
		sourceColumn: sla_tier

	partition dim_environment = m
		mode: import
		source =
			let
				Src = Csv.Document(File.Contents(DataFolder & "dim_environment.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Hdr = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Hdr, {{"environment_key", type text}, {"environment_name", type text}, {"is_production", type logical}, {"sla_tier", type text}})
			in
				Typed
