table fact_ai_usage

	column usage_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		isHidden
		summarizeBy: none
		sourceColumn: usage_date

	column platform_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: platform_key

	column identity_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: identity_key

	column model_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: model_key

	column cost_center_key
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: cost_center_key

	column unit_type
		dataType: string
		summarizeBy: none
		sourceColumn: unit_type

	column quantity
		dataType: double
		formatString: #,0
		summarizeBy: sum
		sourceColumn: quantity

	column input_tokens
		dataType: int64
		formatString: #,0
		isHidden
		summarizeBy: sum
		sourceColumn: input_tokens

	column output_tokens
		dataType: int64
		formatString: #,0
		isHidden
		summarizeBy: sum
		sourceColumn: output_tokens

	column cached_tokens
		dataType: int64
		formatString: #,0
		isHidden
		summarizeBy: sum
		sourceColumn: cached_tokens

	column requests
		dataType: int64
		formatString: #,0
		isHidden
		summarizeBy: sum
		sourceColumn: requests

	column cost_usd
		dataType: double
		formatString: \$#,0.0000
		isHidden
		summarizeBy: sum
		sourceColumn: cost_usd

	column cost_is_estimated
		dataType: boolean
		summarizeBy: none
		sourceColumn: cost_is_estimated

	column is_error
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: is_error

	column latency_ms
		dataType: double
		isHidden
		summarizeBy: none
		sourceColumn: latency_ms


	measure 'Total AI Cost' = SUM(fact_ai_usage[cost_usd])
		formatString: \$#,0.00

	/// Cost sourced from a real billing surface (Foundry gateway rates, GitHub netAmount).
	measure 'Billed Cost' = CALCULATE([Total AI Cost], fact_ai_usage[cost_is_estimated] = FALSE)
		formatString: \$#,0.00

	/// Cost derived from dim_rate_card. Accuracy depends entirely on the customer's rate card.
	measure 'Modelled Cost' = CALCULATE([Total AI Cost], fact_ai_usage[cost_is_estimated] = TRUE)
		formatString: \$#,0.00

	/// Share of total spend that is billed rather than modelled. Put this on page 1.
	measure 'Cost Confidence %' = DIVIDE([Billed Cost], [Total AI Cost])
		formatString: 0.0%

	/// Licence cost. Does not vary with usage.
	measure 'Fixed Cost' =
		CALCULATE([Total AI Cost], fact_ai_usage[unit_type] IN { "seat_day" })
		formatString: \$#,0.00

	/// Consumption cost. The only half a FinOps programme can actually influence.
	measure 'Variable Cost' =
		CALCULATE([Total AI Cost], NOT ( fact_ai_usage[unit_type] IN { "seat_day" } ))
		formatString: \$#,0.00

	measure 'Variable Cost %' = DIVIDE([Variable Cost], [Total AI Cost])
		formatString: 0.0%

	measure 'Total Tokens' =
		CALCULATE(SUM(fact_ai_usage[quantity]), fact_ai_usage[unit_type] = "token")
		formatString: #,0

	measure 'Input Tokens' = SUM(fact_ai_usage[input_tokens])
		formatString: #,0

	measure 'Output Tokens' = SUM(fact_ai_usage[output_tokens])
		formatString: #,0

	measure 'Cached Tokens' = SUM(fact_ai_usage[cached_tokens])
		formatString: #,0

	/// Cached input bills at a lower rate. Direct, actionable saving.
	measure 'Cache Hit Rate' = DIVIDE([Cached Tokens], [Input Tokens])
		formatString: 0.0%

	measure 'Cost per 1K Tokens' =
		DIVIDE(CALCULATE([Total AI Cost], fact_ai_usage[unit_type] = "token"), DIVIDE([Total Tokens], 1000))
		formatString: \$#,0.0000

	measure 'Copilot Credits' =
		CALCULATE(SUM(fact_ai_usage[quantity]), fact_ai_usage[unit_type] = "copilot_credit")
		formatString: #,0

	measure 'Premium Requests' =
		CALCULATE(SUM(fact_ai_usage[quantity]), fact_ai_usage[unit_type] = "premium_request")
		formatString: #,0

	/// Usage signal only. M365 Copilot prompts are never billable.
	measure 'M365 Prompts' =
		CALCULATE(SUM(fact_ai_usage[quantity]), fact_ai_usage[unit_type] = "prompt")
		formatString: #,0

	measure 'Licensed Seats' =
		CALCULATE(DISTINCTCOUNT(fact_ai_usage[identity_key]), fact_ai_usage[unit_type] = "seat_day")
		formatString: #,0

	measure 'Total Requests' = SUM(fact_ai_usage[requests])
		formatString: #,0

	measure 'Active Users' = DISTINCTCOUNT(fact_ai_usage[identity_key])
		formatString: #,0

	measure 'Cost per Active User' = DIVIDE([Total AI Cost], [Active Users])
		formatString: \$#,0.00

	/// Users holding a paid seat with zero activity in 28 days. The recoverable number.
	measure 'Idle Licensed Users' =
		VAR Win = DATESINPERIOD(dim_date[date_key], MAX(dim_date[date_key]), -28, DAY)
		RETURN
		COUNTROWS(
			FILTER(
				VALUES(dim_identity[identity_key]),
				CALCULATE([Licensed Seats], Win) > 0
					&& CALCULATE([M365 Prompts] + [Premium Requests] + [Total Requests], Win) = 0
			)
		)
		formatString: #,0

	measure 'Idle Seat Waste (monthly)' =
		[Idle Licensed Users] * 30 * AVERAGE(dim_rate_card[unit_price_usd])
		formatString: \$#,0.00

	measure 'Error Rate' =
		DIVIDE(CALCULATE([Total Requests], fact_ai_usage[is_error] = "True"), [Total Requests])
		formatString: 0.0%

	measure 'Avg Latency (ms)' =
		AVERAGEX(FILTER(fact_ai_usage, fact_ai_usage[latency_ms] > 0), fact_ai_usage[latency_ms])
		formatString: #,0

	measure 'Cost PM' = CALCULATE([Total AI Cost], DATEADD(dim_date[date_key], -1, MONTH))
		formatString: \$#,0.00

	measure 'MoM Cost Delta %' = DIVIDE([Total AI Cost] - [Cost PM], [Cost PM])
		formatString: +0.0%;-0.0%;0.0%

	measure 'Cost (30d run-rate)' =
		VAR D = COUNTROWS(VALUES(dim_date[date_key]))
		RETURN DIVIDE([Total AI Cost], D) * 30
		formatString: \$#,0.00

	partition fact_ai_usage = m
		mode: import
		source =
			let
				Src = Csv.Document(File.Contents(DataFolder & "fact_ai_usage.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Hdr = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Hdr, {{"usage_date", type date}, {"platform_key", type text}, {"identity_key", type text}, {"model_key", type text}, {"cost_center_key", type text}, {"unit_type", type text}, {"quantity", type number}, {"input_tokens", Int64.Type}, {"output_tokens", Int64.Type}, {"cached_tokens", Int64.Type}, {"requests", Int64.Type}, {"cost_usd", type number}, {"cost_is_estimated", type logical}, {"is_error", type text}, {"latency_ms", type number}})
			in
				Typed
